repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.106.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive

      - id: terraform_validate

      - id: terraform_tflint

      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check=CKV_AWS_136,CKV_AWS_338,CKV_AWS_158,CKV_AWS_91,CKV_AWS_150,CKV_AWS_131,CKV_AWS_333,CKV_AWS_130,CKV_AWS_23,CKV_AWS_382,CKV_AWS_260,CKV_AWS_161,CKV_AWS_133,CKV_AWS_293,CKV_AWS_129,CKV_AWS_157,CKV_AWS_226,CKV_AWS_118,CKV2_AWS_11,CKV2_AWS_12,CKV2_AWS_5,CKV2_AWS_60,CKV_AWS_378,CKV2_AWS_28,CKV_DOCKER_2,CKV_DOCKER_3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace