sonar.projectKey=isaqueslv9_Shelfie-aws-cicd
sonar.organization=isaqueslv9
sonar.projectName=Shelfie

sonar.sources=app
sonar.exclusions=app/img/**,app/css/**,app/js/**,app/templates/**
sonar.php.file.suffixes=.php