sonar.projectKey=seu-usuario_shelfie-mysql
sonar.organization=seu-usuario
sonar.projectName=Shelfie

sonar.sources=app
sonar.exclusions=app/img/**,app/css/**,app/js/**,app/templates/**
sonar.php.file.suffixes=.php