FROM nginx:alpine


RUN apk update && apk upgrade --no-cache && apk add --no-cache curl

# 2.
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY app /var/www/html


RUN chown -R nginx:nginx /var/www/html && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid


HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost/ || exit 1


USER nginx

EXPOSE 80