name: CI —  Validação de build

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build da imagem PHP
        run: docker build -t shelfie-app:ci ./app

      - name: Build da imagem Nginx
        run: docker build -f nginx/dockerfile -t shelfie-nginx:ci .

      - name: Scan de vulnerabilidades imagem PHP com trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: shelfie-app:ci
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Scan de vulnerabilidades imagem Nginx com Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: shelfie-nginx:ci
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'



