name: Build da imagem e verificação de segurança

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  security-events: write

jobs:

  build-and-scan:
    name: Build e Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Scan com gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build imagem PHP
        run: docker build -t shelfie-app:ci ./app

      - name: Build imagem Nginx
        run: docker build -f nginx/dockerfile -t shelfie-nginx:ci .

      - name: Scan imagem PHP com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shelfie-app:ci
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Scan imagem Nginx com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shelfie-nginx:ci
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Scan de codigo com semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: >
            p/php
            p/secrets
            p/owasp-top-ten
      

      - name: CI concluído
        run: echo "Build, e verificações com Trivy e Semgrep passaram. Código aprovado para PR"